# Generated by Django 5.2.14 on 2026-05-09 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caso",
            fields=[
                ("oid_caso", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("numero_expediente", models.CharField(max_length=50, unique=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                ("juzgado", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "verbose_name": "Caso",
                "verbose_name_plural": "Casos",
                "db_table": "caso",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="CodigoLegal",
            fields=[
                ("oid_codigo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_norma", models.CharField(max_length=100)),
                ("numero_articulo", models.CharField(max_length=50)),
                ("texto_contenido", models.TextField()),
                ("vigencia", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Código Legal",
                "verbose_name_plural": "Códigos Legales",
                "db_table": "codigo_legal",
                "ordering": ["nombre_norma", "numero_articulo"],
            },
        ),
        migrations.CreateModel(
            name="EstadoCaso",
            fields=[
                ("oid_estado", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Estado de Caso",
                "verbose_name_plural": "Estados de Caso",
                "db_table": "estado_caso",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("oid_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "rol",
            },
        ),
        migrations.CreateModel(
            name="TipoCaso",
            fields=[
                ("oid_tipo_caso", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Tipo de Caso",
                "verbose_name_plural": "Tipos de Caso",
                "db_table": "tipo_caso",
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                ("oid_documento", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_archivo", models.CharField(max_length=150)),
                ("ruta_archivo", models.FileField(upload_to="documentos/%Y/%m/")),
                ("tipo_documento", models.CharField(max_length=50)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "oid_caso",
                    models.ForeignKey(
                        db_column="oid_caso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="client.caso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "db_table": "documento",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.AddField(
            model_name="caso",
            name="oid_estado",
            field=models.ForeignKey(
                db_column="oid_estado",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos",
                to="client.estadocaso",
            ),
        ),
        migrations.AddField(
            model_name="caso",
            name="oid_tipo_caso",
            field=models.ForeignKey(
                db_column="oid_tipo_caso",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos",
                to="client.tipocaso",
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("oid_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "matricula_profesional",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "especialidad",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "oid_rol",
                    models.ForeignKey(
                        db_column="oid_rol",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="client.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
            },
        ),
        migrations.AddField(
            model_name="caso",
            name="oid_abogado",
            field=models.ForeignKey(
                db_column="oid_abogado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="casos",
                to="client.usuario",
            ),
        ),
        migrations.CreateModel(
            name="CasoNormativa",
            fields=[
                ("oid_relacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_asociacion", models.DateTimeField(auto_now_add=True)),
                (
                    "oid_caso",
                    models.ForeignKey(
                        db_column="oid_caso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normativas",
                        to="client.caso",
                    ),
                ),
                (
                    "oid_codigo",
                    models.ForeignKey(
                        db_column="oid_codigo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casos_asociados",
                        to="client.codigolegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso-Normativa",
                "verbose_name_plural": "Caso-Normativas",
                "db_table": "caso_normativa",
                "unique_together": {("oid_caso", "oid_codigo")},
            },
        ),
    ]
