# Generated by Django 5.2.14 on 2026-05-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caso",
            options={"ordering": ["-fecha_inicio"]},
        ),
        migrations.AlterModelOptions(
            name="casonormativa",
            options={},
        ),
        migrations.AlterModelOptions(
            name="codigolegal",
            options={"ordering": ["nombre_norma", "numero_articulo"]},
        ),
        migrations.AlterModelOptions(
            name="documento",
            options={"ordering": ["-fecha_subida"]},
        ),
        migrations.AlterModelOptions(
            name="estadocaso",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rol",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tipocaso",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
        migrations.AddField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="casonormativa",
            name="oid_caso",
            field=models.ForeignKey(
                db_column="oid_caso",
                on_delete=django.db.models.deletion.CASCADE,
                to="client.caso",
            ),
        ),
        migrations.AlterField(
            model_name="casonormativa",
            name="oid_codigo",
            field=models.ForeignKey(
                db_column="oid_codigo",
                on_delete=django.db.models.deletion.CASCADE,
                to="client.codigolegal",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="oid_caso",
            field=models.ForeignKey(
                db_column="oid_caso",
                on_delete=django.db.models.deletion.CASCADE,
                to="client.caso",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="oid_rol",
            field=models.ForeignKey(
                db_column="oid_rol",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="client.rol",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
