"""Make Notificacion.oid_usuario nullable to allow global notifications.

Generated by copilot patch.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_codigolegal_indices_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="oid_usuario",
            field=models.ForeignKey(
                db_column="oid_usuario",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.usuario",
            ),
        ),
    ]
