# Generated by Django 5.2.15 on 2026-06-21 05:14

import client.gas_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_codigolegal_archivo_pdf_alter_notificacion_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codigolegal",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=client.gas_storage.GASDriveStorage(),
                upload_to="codigos/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="ruta_archivo",
            field=models.FileField(
                storage=client.gas_storage.GASDriveStorage(),
                upload_to="documentos/%Y/%m/",
            ),
        ),
    ]
